title: AI KIA Blog
description: "Exploring how AI replaces human tasks."
remote_theme: mmistakes/minimal-mistakes
head_custom: head-custom.html
include:
  - head-custom.html

defaults:
  -
    scope:
      path: ""
    values:
      include:
        head-custom: "head-custom.html"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
