title: AI KIA Blog
description: "Exploring how AI replaces human tasks."
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

include:
  - _includes/head-custom.html

defaults:
  -
    scope:
      path: ""
    values:
      include:
        head-custom: "head-custom.html"
