title: AI KIA Blog
description: "Exploring how AI replaces human tasks."
baseurl: ""
url: "http://coldbrue.com" 
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Tell theme to include our custom head content
defaults:
  -
    scope:
      path: ""
    values:
      include:
        head-custom: "head-custom.html"





