title: AI KIA Blog
description: Exploring how AI replaces human tasks.
url: "https://coldbrue.com"
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
minimal_mistakes_skin: "neon"
