title: AI KIA Blog
description: "Exploring how AI replaces human tasks."
remote_theme: mmistakes/minimal-mistakes
head_custom: head-custom.html
# Minimal Mistakes theme settings
include:
  - _includes/head-custom.html

plugins:
  - jekyll-feed
  - jekyll-seo-tag
