title: AI KIA Blog
description: "Exploring how AI replaces human tasks."
theme: minimal-mistakes-jekyll

# Needed to load head-custom.html
head_custom: head-custom.html

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
